# Generated by Django 4.2.23 on 2025-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('form', 'form'), ('gender', 'gender')], max_length=100),
        ),
    ]
