# Generated by Django 4.2.23 on 2025-08-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product_gallery'},
        ),
    ]
