# Generated by Django 5.2.5 on 2025-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20250814_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('gender', 'gender'), ('form', 'form')], max_length=100),
        ),
    ]
