# Generated by Django 5.2.5 on 2025-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('form', 'form'), ('gender', 'gender')], max_length=100),
        ),
    ]
