# Generated by Django 4.2.23 on 2025-08-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
